### ISSUE TITLE
Maintain the folder structure

### ISSUE THREAD

**Issue by anuragdaksh7** [anuragdaksh7/web-based-expense-tracker#20]

**Comment by aEmirturkoglu** [comment]
I forgot to say this is my first contribution to an open source project btw and thanks for your time.

**Comment by anuragdaksh7** [comment]
okay, but make sure the functionality of code
also you can make a pull request so I can review the code

**Comment by aEmirturkoglu** [comment]
ok I did a commit now and do i have to push it to origin master?

**Comment by anuragdaksh7** [comment]
yeah it would open a PR to be reviewed

**Comment by anuragdaksh7** [comment]
steps to contribute to a open source project:
- fork the parent repo
- git clone forked repo
- make a new branch 
- do stuff in branch
- then push that branch 
- then raise a PR

**Comment by aEmirturkoglu** [comment]
did you get any pr?

**Comment by anuragdaksh7** [comment]
yes let me see it
